### ISSUE TITLE
chmod: cannot access '/tmp/Sen2Cor-02.05.00-Linux64.run': No such file or directory

### ISSUE THREAD

**Issue by iliasmachairas** [frontiersi/docker-sen2cor-example#1]
I tried to create run the docker-composer as you suggest but it did not work out.  The following error pops up "#0 0.292 chmod: cannot access '/tmp/Sen2Cor-02.05.00-Linux64.run': No such file or directory".  

I added "RUN mkdir /tmp" but the file exists. I get the following error: "#0 0.218 mkdir: cannot create directory '/tmp': File exists"

**Comment by neteler** [comment]
FWIW, I have forked this repo (thanks @alexgleith for your work!) and updated it to sen2cor 2.10:

https://github.com/mundialis/docker-sen2cor

**Comment by alexgleith** [comment]
Awesome work, thank you!
